### ISSUE TITLE
Unable to obtain point cloud results

### ISSUE THREAD

**Issue by YSYYU** [vkvats/GC-MVSNet#4]
Why am I unable to obtain the point cloud file when running the test.py file and test_dtu.sh file, regardless of whether the filter method is selected as' normal 'or' gipuma ', in the' ply_local 'folder?

**Comment by YSYYU** [comment]
I received the following error while running the test.py file.
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/environment/miniconda3/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/featurize/GC-MVSNet/test.py", line 415, in pcd_filter_worker
    filter_depth(pair_folder, scan_folder, out_folder, os.path.join(args.outdir, save_name))
  File "/home/featurize/GC-MVSNet/test.py", line 395, in filter_depth
    PlyData([el]).write(plyfilename)
  File "/environment/miniconda3/lib/python3.10/site-packages/plyfile.py", line 195, in write
    (must_close, stream) = _open_stream(stream, 'write')
  File "/environment/miniconda3/lib/python3.10/site-packages/plyfile.py", line 1345, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: './outputs/normal_fusion/mvsnet004_l3.ply'

**Comment by zhangqi-eiq** [comment]
Resizing globalstate to 18
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) ./modules/core/src/merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'merge'

**Comment by 12wANG233** [comment]
May I ask if this problem has been solved? I also encountered the same problem.
